export type ProjectDetails = {
  id: number;
  title: string;
  slug: string;
  deal_project_id: number;
  deal_stage_id: number;
  deal_user_id: number;
  deal_person_id: number;
  deal_organization_id: number;
  status: string;
  deal_value: number;
  priority: string;
  due_date: string;
  value_in: string;
  add_time: string;
  update_time: string;
  close_time: string;
  description: string;
  card_id: number;
  language: string;
  created_at: '2024-02-06T23:02:30.000Z';
  project_notes: [];
  quotes: [];
  courses: [];
};
